### ISSUE TITLE
ScreenShot Skewed

### ISSUE THREAD

**Issue by eclectic-tech** [khanhas/MagickMeter#4] opened 2018-08-28 15:31 UTC
If I create a simple screenshot, the image is skewed
    
    [MagickMeter_1]
    Measure = Plugin
    Plugin = MagickMeter
    ;Take screenshot
    Image = File Screenshot | Ignore 1
    ;Crop blurred screenshot to smaller piece base on skin position.
    Image2 = Clone Image | Crop #CURRENTCONFIGX#,#CURRENTCONFIGY#,452,452
    
    [M1]
    Meter=Image
    MeasureName = MagickMeter_1

Tested in Rainmeter v4.2.0.3111 and v4.3.0.3237 with the same result.
Thanks

**Comment by khanhas** [comment] 2018-08-28 17:50
Your code works normally on mine.
How skewed is it?

**Comment by khanhas** [comment] 2018-08-28 18:09
Hmm, I just tried with 4.3. Still works normally. 
I also did try with different scaling in Windows 10 but it's still fine.

**Comment by eclectic-tech** [comment] 2018-08-28 19:25
Just realized I have an older version of your plugin... :(
I will download the latest and get back to you...

Windows 10 Pro
Version 1803
OS Build 17738.1000
With V0.3.0.0 of your plugin it looks like this:
![image](https://user-images.githubusercontent.com/2169788/44744853-1a8c6f80-aad4-11e8-9a91-c9a2ed8eedef.png)

**Comment by khanhas** [comment] 2018-08-28 19:35
Oh my, that's weird.
How about only
```
Image = File Screenshot
```
without any effect?
Is it distorted?

**Comment by eclectic-tech** [comment] 2018-08-28 19:39
Updated MagickMeter.dll to V0.5.0.0 but have the same result with the screenshot code.
However, my screen resolution is normally 1366x768...
If I increase my resolution to 1920x1080, the code does not skew the screenshot

Hope this helps point to where there is a problem for me.

**Comment by eclectic-tech** [comment] 2018-08-28 19:44
Tried:
    
    Image = File Screenshot
    
Still distorted with 1366x768 @ 100% scale

EDIT: I have unadorned onboard graphics capabilities: 
Intel(R) Q45/Q43 Express Chipset (Microsoft Corporation - WDDM 1.1)

**Comment by khanhas** [comment] 2018-08-28 20:01
This is really weird. I do not think I know the cause.
It only happens in 1366x768 resolution. 
Screenshot's also distorted in ImageMagick commandline program, you can try this if you want:
```
magick screenshot: D:\lmao.png
```
I will open an issue in ImageMagick repository.

**Comment by eclectic-tech** [comment] 2018-08-28 20:07
Whoa! Okay, thanks for looking in to this... 

I really was looking forward to using your dll in a few skin ideas I have, but I will wait to see what happens from your inquiry to ImageMagick.

Thanks again!

**Comment by khanhas** [comment] 2018-08-28 20:16
Thank you too!
At this moment, if you want to work with it, I guess you need to use another resolution for your screen, 1360x768 maybe?

**Comment by khanhas** [comment] 2018-09-24 05:41
This bug is fixed in ImageMagick 7.0.8-12  
Just download and install latest version in: https://www.imagemagick.org/script/download.php  
Thanks @eclectic-tech for the report !

**Closed as completed by khanhas** 2018-09-24 05:41 UTC
